environment: production
python_version: 3.10.0
packages:
     - package_name: cudatoolkit
       version: 11.2
     - package_name: cudnn
       version: 8.1.0 
     - package_name: Tensorflow
       version: 2.10.1
     - package_name: Keras
       version: 2.10.0 
     - package_name: scikit-learn
       version: 1.3.0 
# I will add more packages and their versions as we go along 